fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("HINDSIGHT_CORE_H")
        .with_autogen_warning("/* Auto-generated by cbindgen. Do not modify. */")
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file("hindsight_core.h");
}
